-a 密码
-c 以集群形式发出命令，可以避免ACK和MOVE
-h 主机名
-p 端口号
-r 命令重复次数
-i 间隔秒数（和-r一起用）
-n 指定db，默认操作都在db0，-n 1表示在db1上操作

-raw 以原始形式显示信息
--stat 详细统计信息
--bigkeys 大键扫描
--latency 有三个选项，--latency、--latency-history、--latency-dist
